<template>
  <div class="
      tw-w-full
      tw-h-screen
      tw--mt-64
      tw-bg-gradient-to-t
      tw-to-primary-800
      tw-from-primary-400
  ">
    <div class="
      tw-w-full
      tw-flex
      tw-px-32
      tw-max-w-page
      tw-absolute
      tw-top-1/2
      tw-left-1/2
      tw-transform
          tw--translate-x-1/2
          tw--translate-y-1/2
      tw-w-full
    ">
      <div class="tw-self-center tw-w-2/5 tw-pr-32">
        <h1 class="tw-text-6xl tw-leading-tight tw-text-white tw-font-bold">Verdien geld als Locato host</h1>
        <p class="tw-mt-24 tw-text-white">Begin met het verhuren van je ruimte voor foto shoots, events, vergaderingen of andere creatieve doeleinden.</p>
        <v-autocomplete
            class="tw-mt-24"
            v-model="activity"
            :items="activities"
            :loading="isLoadingActivities"
            color="primary"
            solo-inverted
            dark
            hide-no-data
            hide-selected
            item-text="name"
            item-value="id"
            label="Wat voor ruimte wil je verhuren?"
            placeholder="Typ om te zoeken"
            hide-details
            return-object
            clearable
        ></v-autocomplete>
        <v-btn
            class="tw-w-full tw-font-bold tw-mt-16"
            color="white"
            :disabled="isDisabled"
            tile
            large
            @click="startRegistration"
        >
            Starten
        </v-btn>
      </div>
      <div class="tw-w-3/5 tw-pl-32">
        <img class="fade-in-right" src="@/assets/images/photo-studio-light.jpg">
      </div>
    </div>
  </div>
</template>

<script lang="ts">
  import { Component, Vue } from 'vue-property-decorator';
  import _ from 'lodash';
  import { Activity } from '~/models/Activity';

  @Component<Profile>({
    components: {}
  })
  export default class Profile extends Vue {
    protected activity: Activity | null = null;

    protected activities: Activity[] = [];

    protected isLoadingActivities = true;

    protected isLoading = true;

    protected async mounted(): Promise<void> {
      await this.getActivities();
      this.isLoading = false;
    }

    protected startRegistration(): void {
      if (!this.$store.getters['Auth/isAuthenticated']) {
        this.$store.commit('Auth/showAuthModal', true);
      } else {

      } 
    }

    protected async getActivities(): Promise<void> {
      await new Activity().list()
      .then((activities: Activity[]) => {
          this.activities = activities;
          this.isLoadingActivities = false;
      })
      .catch((error: any) => console.log(error));
    }

    protected get isDisabled(): boolean {
      return !this.activity;
    }
  }
</script>

<style lang="scss">
  .fade-in-right {
    -webkit-animation: fade-in-right 0.6s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
            animation: fade-in-right 0.6s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  }

  /* ----------------------------------------------
  * Generated by Animista on 2021-4-7 17:53:41
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info. 
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

  /**
  * ----------------------------------------
  * animation fade-in-right
  * ----------------------------------------
  */
  @-webkit-keyframes fade-in-right {
    0% {
      -webkit-transform: translateX(25px);
              transform: translateX(25px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateX(0);
              transform: translateX(0);
      opacity: 1;
    }
  }
  @keyframes fade-in-right {
    0% {
      -webkit-transform: translateX(25px);
              transform: translateX(25px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateX(0);
              transform: translateX(0);
      opacity: 1;
    }
  }

</style>